/* This file is generated by frontend/scripts/generateAssetManifest.mjs. */
import type { GeneratedAssetManifest } from "./assetManifest";

export const generatedAssetManifest = {
  "images": [
    {
      "key": "fluff",
      "path": "/assets/fluff.jpeg",
      "filename": "fluff.jpeg",
      "extension": "jpeg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "honors_fpdc_awards",
      "path": "/assets/honors/FPDC_Awards.jpeg",
      "filename": "FPDC_Awards.jpeg",
      "extension": "jpeg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "honors_fpdc_award_ceremony",
      "path": "/assets/honors/FPDC_Award_Ceremony.jpeg",
      "filename": "FPDC_Award_Ceremony.jpeg",
      "extension": "jpeg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "honors_imo_certificate",
      "path": "/assets/honors/imo-certificate.png",
      "filename": "imo-certificate.png",
      "extension": "png",
      "inferredType": "background",
      "width": 933,
      "height": 687,
      "suggestedFrameWidth": 933,
      "suggestedFrameHeight": 687,
      "frameCount": 1
    },
    {
      "key": "honors_imo_group",
      "path": "/assets/honors/IMO_Group.jpeg",
      "filename": "IMO_Group.jpeg",
      "extension": "jpeg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "honors_pmun_awards",
      "path": "/assets/honors/PMUN_Awards.jpeg",
      "filename": "PMUN_Awards.jpeg",
      "extension": "jpeg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "honors_pmun_logo",
      "path": "/assets/honors/PMUN_logo.jpeg",
      "filename": "PMUN_logo.jpeg",
      "extension": "jpeg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "honors_pmun_me",
      "path": "/assets/honors/PMUN_Me.jpeg",
      "filename": "PMUN_Me.jpeg",
      "extension": "jpeg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "projects_commoncrawl_mapreduce",
      "path": "/assets/projects/commoncrawl_mapreduce.png",
      "filename": "commoncrawl_mapreduce.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1536,
      "height": 1024,
      "suggestedFrameWidth": 1536,
      "suggestedFrameHeight": 1024,
      "frameCount": 1
    },
    {
      "key": "projects_cyclegan",
      "path": "/assets/projects/cycleGAN.png",
      "filename": "cycleGAN.png",
      "extension": "png",
      "inferredType": "background",
      "width": 828,
      "height": 740,
      "suggestedFrameWidth": 828,
      "suggestedFrameHeight": 740,
      "frameCount": 1
    },
    {
      "key": "projects_english_to_urdu_mbart50",
      "path": "/assets/projects/english_to_urdu_mbart50.png",
      "filename": "english_to_urdu_mbart50.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1092,
      "height": 905,
      "suggestedFrameWidth": 1092,
      "suggestedFrameHeight": 905,
      "frameCount": 1
    },
    {
      "key": "projects_event_booking_system_architecture",
      "path": "/assets/projects/Event-Booking_System-Architecture.png",
      "filename": "Event-Booking_System-Architecture.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1536,
      "height": 1024,
      "suggestedFrameWidth": 1536,
      "suggestedFrameHeight": 1024,
      "frameCount": 1
    },
    {
      "key": "projects_financial_sentiment_pipeline_architecture",
      "path": "/assets/projects/financial_sentiment_pipeline_architecture.png",
      "filename": "financial_sentiment_pipeline_architecture.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1536,
      "height": 1024,
      "suggestedFrameWidth": 1536,
      "suggestedFrameHeight": 1024,
      "frameCount": 1
    },
    {
      "key": "projects_hotel_booking",
      "path": "/assets/projects/hotel_booking.png",
      "filename": "hotel_booking.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1215,
      "height": 618,
      "suggestedFrameWidth": 1215,
      "suggestedFrameHeight": 618,
      "frameCount": 1
    },
    {
      "key": "projects_multimodal_rag",
      "path": "/assets/projects/multimodal rag.png",
      "filename": "multimodal rag.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1896,
      "height": 867,
      "suggestedFrameWidth": 1896,
      "suggestedFrameHeight": 867,
      "frameCount": 1
    },
    {
      "key": "projects_multimodal_rag",
      "path": "/assets/projects/multimodal-RAG.png",
      "filename": "multimodal-RAG.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1536,
      "height": 1024,
      "suggestedFrameWidth": 1536,
      "suggestedFrameHeight": 1024,
      "frameCount": 1
    },
    {
      "key": "projects_nyc_taxi_kafka",
      "path": "/assets/projects/nyc_taxi_kafka.png",
      "filename": "nyc_taxi_kafka.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1920,
      "height": 1020,
      "suggestedFrameWidth": 1920,
      "suggestedFrameHeight": 1020,
      "frameCount": 1
    },
    {
      "key": "projects_online_catalog_png",
      "path": "/assets/projects/online-catalog-png.png",
      "filename": "online-catalog-png.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1432,
      "height": 721,
      "suggestedFrameWidth": 1432,
      "suggestedFrameHeight": 721,
      "frameCount": 1
    },
    {
      "key": "projects_parbutterfly",
      "path": "/assets/projects/parbutterfly.png",
      "filename": "parbutterfly.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1372,
      "height": 772,
      "suggestedFrameWidth": 1372,
      "suggestedFrameHeight": 772,
      "frameCount": 1
    },
    {
      "key": "projects_plant_disease_detection_apache_spark",
      "path": "/assets/projects/plant_disease_detection_apache_spark.png",
      "filename": "plant_disease_detection_apache_spark.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1918,
      "height": 871,
      "suggestedFrameWidth": 1918,
      "suggestedFrameHeight": 871,
      "frameCount": 1
    },
    {
      "key": "projects_pose2play_system_architecture_diagram",
      "path": "/assets/projects/pose2play - System_Architecture_Diagram.png",
      "filename": "pose2play - System_Architecture_Diagram.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1672,
      "height": 941,
      "suggestedFrameWidth": 1672,
      "suggestedFrameHeight": 941,
      "frameCount": 1
    },
    {
      "key": "projects_real_time_crime",
      "path": "/assets/projects/real-time-crime.png",
      "filename": "real-time-crime.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1920,
      "height": 1020,
      "suggestedFrameWidth": 1920,
      "suggestedFrameHeight": 1020,
      "frameCount": 1
    },
    {
      "key": "projects_semantic_product_search",
      "path": "/assets/projects/semantic_product_search.png",
      "filename": "semantic_product_search.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1024,
      "height": 1536,
      "suggestedFrameWidth": 1024,
      "suggestedFrameHeight": 1536,
      "frameCount": 1
    },
    {
      "key": "projects_synthetic_music_detection_architecture",
      "path": "/assets/projects/synthetic_music_detection_architecture.png",
      "filename": "synthetic_music_detection_architecture.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1536,
      "height": 1024,
      "suggestedFrameWidth": 1536,
      "suggestedFrameHeight": 1024,
      "frameCount": 1
    },
    {
      "key": "projects_torcs",
      "path": "/assets/projects/torcs.jpg",
      "filename": "torcs.jpg",
      "extension": "jpg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "projects_urdu_poetry_generation",
      "path": "/assets/projects/urdu_poetry_generation.jpg",
      "filename": "urdu_poetry_generation.jpg",
      "extension": "jpg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "rooms_whitespace_tileset",
      "path": "/assets/rooms/whitespace_tileset.png",
      "filename": "whitespace_tileset.png",
      "extension": "png",
      "inferredType": "tileset",
      "width": 288,
      "height": 128,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 36
    },
    {
      "key": "rooms_white_screen",
      "path": "/assets/rooms/white_screen.png",
      "filename": "white_screen.png",
      "extension": "png",
      "inferredType": "background",
      "width": 640,
      "height": 544,
      "suggestedFrameWidth": 640,
      "suggestedFrameHeight": 544,
      "frameCount": 1
    },
    {
      "key": "sprites_character_omori",
      "path": "/assets/sprites/character_omori.png",
      "filename": "character_omori.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 500,
      "height": 453,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 868
    },
    {
      "key": "sprites_dialogue",
      "path": "/assets/sprites/dialogue-.png",
      "filename": "dialogue-.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 392,
      "height": 96,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 144
    },
    {
      "key": "sprites_dialogue_box",
      "path": "/assets/sprites/dialogue_box.png",
      "filename": "dialogue_box.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 409,
      "height": 113,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 175
    },
    {
      "key": "sprites_dialogue_box_2",
      "path": "/assets/sprites/dialogue_box_2.jpg",
      "filename": "dialogue_box_2.jpg",
      "extension": "jpg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "sprites_dialogue_box_2_frame",
      "path": "/assets/sprites/dialogue_box_2_frame.png",
      "filename": "dialogue_box_2_frame.png",
      "extension": "png",
      "inferredType": "background",
      "width": 590,
      "height": 116,
      "suggestedFrameWidth": 590,
      "suggestedFrameHeight": 116,
      "frameCount": 1
    },
    {
      "key": "sprites_education",
      "path": "/assets/sprites/education.png",
      "filename": "education.png",
      "extension": "png",
      "inferredType": "singleSprite",
      "width": 30,
      "height": 32,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 2
    },
    {
      "key": "sprites_honors",
      "path": "/assets/sprites/honors.png",
      "filename": "honors.png",
      "extension": "png",
      "inferredType": "singleSprite",
      "width": 28,
      "height": 32,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 2
    },
    {
      "key": "sprites_hud_battleui",
      "path": "/assets/sprites/HUD_battleUI.png",
      "filename": "HUD_battleUI.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1472,
      "height": 1389,
      "suggestedFrameWidth": 1472,
      "suggestedFrameHeight": 1389,
      "frameCount": 1
    },
    {
      "key": "sprites_items_charms",
      "path": "/assets/sprites/items_charms.png",
      "filename": "items_charms.png",
      "extension": "png",
      "inferredType": "background",
      "width": 756,
      "height": 972,
      "suggestedFrameWidth": 756,
      "suggestedFrameHeight": 972,
      "frameCount": 1
    },
    {
      "key": "sprites_items_misc",
      "path": "/assets/sprites/items_misc.png",
      "filename": "items_misc.png",
      "extension": "png",
      "inferredType": "objectSheet",
      "width": 1024,
      "height": 1024,
      "suggestedFrameWidth": 64,
      "suggestedFrameHeight": 64,
      "frameCount": 256
    },
    {
      "key": "sprites_lightbulb",
      "path": "/assets/sprites/lightbulb.png",
      "filename": "lightbulb.png",
      "extension": "png",
      "inferredType": "singleSprite",
      "width": 35,
      "height": 61,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 6
    },
    {
      "key": "sprites_tileset_blackspace",
      "path": "/assets/sprites/tileset_blackspace.png",
      "filename": "tileset_blackspace.png",
      "extension": "png",
      "inferredType": "tileset",
      "width": 1024,
      "height": 3072,
      "suggestedFrameWidth": 64,
      "suggestedFrameHeight": 64,
      "frameCount": 768
    },
    {
      "key": "sprites_whitespace_lightbulb",
      "path": "/assets/sprites/whitespace_lightbulb.png",
      "filename": "whitespace_lightbulb.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 288,
      "height": 128,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 36
    },
    {
      "key": "sprites_whitespace_misc",
      "path": "/assets/sprites/whitespace_misc.png",
      "filename": "whitespace_misc.png",
      "extension": "png",
      "inferredType": "objectSheet",
      "width": 564,
      "height": 256,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 560
    }
  ],
  "audio": [
    {
      "key": "audio_bgm_solo_duet",
      "path": "/assets/audio/bgm/solo_duet.ogg",
      "filename": "solo_duet.ogg",
      "extension": "ogg",
      "inferredCategory": "music"
    },
    {
      "key": "audio_bgm_user_title",
      "path": "/assets/audio/bgm/user_title.ogg",
      "filename": "user_title.ogg",
      "extension": "ogg",
      "inferredCategory": "music"
    },
    {
      "key": "audio_bgm_whitespace_piano",
      "path": "/assets/audio/bgm/whitespace_piano.ogg",
      "filename": "whitespace_piano.ogg",
      "extension": "ogg",
      "inferredCategory": "music"
    },
    {
      "key": "audio_sound_effects_ambience_amb_forest_ambience",
      "path": "/assets/audio/sound_effects/ambience/AMB_forest_ambience.ogg",
      "filename": "AMB_forest_ambience.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_ambience_amb_slide_ambience",
      "path": "/assets/audio/sound_effects/ambience/AMB_slide_ambience.ogg",
      "filename": "AMB_slide_ambience.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_ambience_se_machine_hum",
      "path": "/assets/audio/sound_effects/ambience/SE_machine_hum.ogg",
      "filename": "SE_machine_hum.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_ambience_se_static",
      "path": "/assets/audio/sound_effects/ambience/SE_static.ogg",
      "filename": "SE_static.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_interactions_se_cassette_insert",
      "path": "/assets/audio/sound_effects/interactions/SE_Cassette_insert.ogg",
      "filename": "SE_Cassette_insert.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_laptop",
      "path": "/assets/audio/sound_effects/interactions/SE_Laptop.ogg",
      "filename": "SE_Laptop.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_slide_change",
      "path": "/assets/audio/sound_effects/interactions/SE_slide_change.ogg",
      "filename": "SE_slide_change.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_turn_page",
      "path": "/assets/audio/sound_effects/interactions/SE_turn_page.ogg",
      "filename": "SE_turn_page.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_tv_blip",
      "path": "/assets/audio/sound_effects/interactions/SE_TV_BLIP.ogg",
      "filename": "SE_TV_BLIP.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_movement_ft_big_reverb",
      "path": "/assets/audio/sound_effects/movement/ft_big_reverb.ogg",
      "filename": "ft_big_reverb.ogg",
      "extension": "ogg",
      "inferredCategory": "movement"
    },
    {
      "key": "audio_sound_effects_movement_ft_sand",
      "path": "/assets/audio/sound_effects/movement/ft_sand.ogg",
      "filename": "ft_sand.ogg",
      "extension": "ogg",
      "inferredCategory": "movement"
    },
    {
      "key": "audio_sound_effects_transitions_se_spiral_down",
      "path": "/assets/audio/sound_effects/transitions/SE_spiral_down.ogg",
      "filename": "SE_spiral_down.ogg",
      "extension": "ogg",
      "inferredCategory": "transition"
    },
    {
      "key": "audio_sound_effects_transitions_se_spiral_up",
      "path": "/assets/audio/sound_effects/transitions/SE_spiral_up.ogg",
      "filename": "SE_spiral_up.ogg",
      "extension": "ogg",
      "inferredCategory": "transition"
    },
    {
      "key": "audio_sound_effects_ui_gen_item_get",
      "path": "/assets/audio/sound_effects/UI/GEN_item_get.ogg",
      "filename": "GEN_item_get.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_se_click",
      "path": "/assets/audio/sound_effects/UI/SE_click.ogg",
      "filename": "SE_click.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_sys_cursor",
      "path": "/assets/audio/sound_effects/UI/SYS_cursor.ogg",
      "filename": "SYS_cursor.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_sys_quest_complete",
      "path": "/assets/audio/sound_effects/UI/SYS_quest_complete.ogg",
      "filename": "SYS_quest_complete.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_sys_select",
      "path": "/assets/audio/sound_effects/UI/SYS_select.ogg",
      "filename": "SYS_select.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    }
  ]
} as const satisfies GeneratedAssetManifest;
