/* This file is generated by frontend/scripts/generateAssetManifest.mjs. */
import type { GeneratedAssetManifest } from "./assetManifest";

export const generatedAssetManifest = {
  "images": [
    {
      "key": "rooms_whitespace_tileset",
      "path": "/assets/rooms/whitespace_tileset.png",
      "filename": "whitespace_tileset.png",
      "extension": "png",
      "inferredType": "tileset",
      "width": 288,
      "height": 128,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 36
    },
    {
      "key": "rooms_white_screen",
      "path": "/assets/rooms/white_screen.png",
      "filename": "white_screen.png",
      "extension": "png",
      "inferredType": "background",
      "width": 640,
      "height": 544,
      "suggestedFrameWidth": 640,
      "suggestedFrameHeight": 544,
      "frameCount": 1
    },
    {
      "key": "sprites_character_omori",
      "path": "/assets/sprites/character_omori.png",
      "filename": "character_omori.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 500,
      "height": 453,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 868
    },
    {
      "key": "sprites_dialogue",
      "path": "/assets/sprites/dialogue-.png",
      "filename": "dialogue-.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 392,
      "height": 96,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 144
    },
    {
      "key": "sprites_dialogue_box",
      "path": "/assets/sprites/dialogue_box.png",
      "filename": "dialogue_box.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 409,
      "height": 113,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 175
    },
    {
      "key": "sprites_dialogue_box_2",
      "path": "/assets/sprites/dialogue_box_2.jpg",
      "filename": "dialogue_box_2.jpg",
      "extension": "jpg",
      "inferredType": "singleSprite",
      "width": 0,
      "height": 0,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 0
    },
    {
      "key": "sprites_dialogue_box_2_frame",
      "path": "/assets/sprites/dialogue_box_2_frame.png",
      "filename": "dialogue_box_2_frame.png",
      "extension": "png",
      "inferredType": "background",
      "width": 590,
      "height": 116,
      "suggestedFrameWidth": 590,
      "suggestedFrameHeight": 116,
      "frameCount": 1
    },
    {
      "key": "sprites_education",
      "path": "/assets/sprites/education.png",
      "filename": "education.png",
      "extension": "png",
      "inferredType": "singleSprite",
      "width": 30,
      "height": 32,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 2
    },
    {
      "key": "sprites_honors",
      "path": "/assets/sprites/honors.png",
      "filename": "honors.png",
      "extension": "png",
      "inferredType": "singleSprite",
      "width": 28,
      "height": 32,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 2
    },
    {
      "key": "sprites_hud_battleui",
      "path": "/assets/sprites/HUD_battleUI.png",
      "filename": "HUD_battleUI.png",
      "extension": "png",
      "inferredType": "background",
      "width": 1472,
      "height": 1389,
      "suggestedFrameWidth": 1472,
      "suggestedFrameHeight": 1389,
      "frameCount": 1
    },
    {
      "key": "sprites_items_charms",
      "path": "/assets/sprites/items_charms.png",
      "filename": "items_charms.png",
      "extension": "png",
      "inferredType": "background",
      "width": 756,
      "height": 972,
      "suggestedFrameWidth": 756,
      "suggestedFrameHeight": 972,
      "frameCount": 1
    },
    {
      "key": "sprites_items_misc",
      "path": "/assets/sprites/items_misc.png",
      "filename": "items_misc.png",
      "extension": "png",
      "inferredType": "objectSheet",
      "width": 1024,
      "height": 1024,
      "suggestedFrameWidth": 64,
      "suggestedFrameHeight": 64,
      "frameCount": 256
    },
    {
      "key": "sprites_lightbulb",
      "path": "/assets/sprites/lightbulb.png",
      "filename": "lightbulb.png",
      "extension": "png",
      "inferredType": "singleSprite",
      "width": 35,
      "height": 61,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 6
    },
    {
      "key": "sprites_tileset_blackspace",
      "path": "/assets/sprites/tileset_blackspace.png",
      "filename": "tileset_blackspace.png",
      "extension": "png",
      "inferredType": "tileset",
      "width": 1024,
      "height": 3072,
      "suggestedFrameWidth": 64,
      "suggestedFrameHeight": 64,
      "frameCount": 768
    },
    {
      "key": "sprites_whitespace_lightbulb",
      "path": "/assets/sprites/whitespace_lightbulb.png",
      "filename": "whitespace_lightbulb.png",
      "extension": "png",
      "inferredType": "spriteSheet",
      "width": 288,
      "height": 128,
      "suggestedFrameWidth": 32,
      "suggestedFrameHeight": 32,
      "frameCount": 36
    },
    {
      "key": "sprites_whitespace_misc",
      "path": "/assets/sprites/whitespace_misc.png",
      "filename": "whitespace_misc.png",
      "extension": "png",
      "inferredType": "objectSheet",
      "width": 564,
      "height": 256,
      "suggestedFrameWidth": 16,
      "suggestedFrameHeight": 16,
      "frameCount": 560
    }
  ],
  "audio": [
    {
      "key": "audio_bgm_solo_duet",
      "path": "/assets/audio/bgm/solo_duet.ogg",
      "filename": "solo_duet.ogg",
      "extension": "ogg",
      "inferredCategory": "music"
    },
    {
      "key": "audio_bgm_user_title",
      "path": "/assets/audio/bgm/user_title.ogg",
      "filename": "user_title.ogg",
      "extension": "ogg",
      "inferredCategory": "music"
    },
    {
      "key": "audio_bgm_whitespace_piano",
      "path": "/assets/audio/bgm/whitespace_piano.ogg",
      "filename": "whitespace_piano.ogg",
      "extension": "ogg",
      "inferredCategory": "music"
    },
    {
      "key": "audio_sound_effects_ambience_amb_forest_ambience",
      "path": "/assets/audio/sound_effects/ambience/AMB_forest_ambience.ogg",
      "filename": "AMB_forest_ambience.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_ambience_amb_slide_ambience",
      "path": "/assets/audio/sound_effects/ambience/AMB_slide_ambience.ogg",
      "filename": "AMB_slide_ambience.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_ambience_se_machine_hum",
      "path": "/assets/audio/sound_effects/ambience/SE_machine_hum.ogg",
      "filename": "SE_machine_hum.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_ambience_se_static",
      "path": "/assets/audio/sound_effects/ambience/SE_static.ogg",
      "filename": "SE_static.ogg",
      "extension": "ogg",
      "inferredCategory": "ambience"
    },
    {
      "key": "audio_sound_effects_interactions_se_cassette_insert",
      "path": "/assets/audio/sound_effects/interactions/SE_Cassette_insert.ogg",
      "filename": "SE_Cassette_insert.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_laptop",
      "path": "/assets/audio/sound_effects/interactions/SE_Laptop.ogg",
      "filename": "SE_Laptop.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_slide_change",
      "path": "/assets/audio/sound_effects/interactions/SE_slide_change.ogg",
      "filename": "SE_slide_change.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_turn_page",
      "path": "/assets/audio/sound_effects/interactions/SE_turn_page.ogg",
      "filename": "SE_turn_page.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_interactions_se_tv_blip",
      "path": "/assets/audio/sound_effects/interactions/SE_TV_BLIP.ogg",
      "filename": "SE_TV_BLIP.ogg",
      "extension": "ogg",
      "inferredCategory": "interaction"
    },
    {
      "key": "audio_sound_effects_movement_ft_big_reverb",
      "path": "/assets/audio/sound_effects/movement/ft_big_reverb.ogg",
      "filename": "ft_big_reverb.ogg",
      "extension": "ogg",
      "inferredCategory": "movement"
    },
    {
      "key": "audio_sound_effects_movement_ft_sand",
      "path": "/assets/audio/sound_effects/movement/ft_sand.ogg",
      "filename": "ft_sand.ogg",
      "extension": "ogg",
      "inferredCategory": "movement"
    },
    {
      "key": "audio_sound_effects_transitions_se_spiral_down",
      "path": "/assets/audio/sound_effects/transitions/SE_spiral_down.ogg",
      "filename": "SE_spiral_down.ogg",
      "extension": "ogg",
      "inferredCategory": "transition"
    },
    {
      "key": "audio_sound_effects_transitions_se_spiral_up",
      "path": "/assets/audio/sound_effects/transitions/SE_spiral_up.ogg",
      "filename": "SE_spiral_up.ogg",
      "extension": "ogg",
      "inferredCategory": "transition"
    },
    {
      "key": "audio_sound_effects_ui_gen_item_get",
      "path": "/assets/audio/sound_effects/UI/GEN_item_get.ogg",
      "filename": "GEN_item_get.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_se_click",
      "path": "/assets/audio/sound_effects/UI/SE_click.ogg",
      "filename": "SE_click.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_sys_cursor",
      "path": "/assets/audio/sound_effects/UI/SYS_cursor.ogg",
      "filename": "SYS_cursor.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_sys_quest_complete",
      "path": "/assets/audio/sound_effects/UI/SYS_quest_complete.ogg",
      "filename": "SYS_quest_complete.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    },
    {
      "key": "audio_sound_effects_ui_sys_select",
      "path": "/assets/audio/sound_effects/UI/SYS_select.ogg",
      "filename": "SYS_select.ogg",
      "extension": "ogg",
      "inferredCategory": "ui"
    }
  ]
} as const satisfies GeneratedAssetManifest;
