import type { RoomObject } from "../../types";
import type { ObjectSpriteKey } from "./spriteConfig";

export interface InteractableObjectConfig {
  id: string;
  displayName: string;
  label: string;
  assetKey: ObjectSpriteKey;
  x: number;
  y: number;
  width: number;
  height: number;
  interactionRadius: number;
  interactionPrompt: string;
  actionType: RoomObject["interaction_type"];
  targetSection: RoomObject["linked_portfolio_section"];
  color: number;
  accent: number;
}

export const interactableObjects: InteractableObjectConfig[] = [
  {
    id: "laptop",
    displayName: "Laptop",
    label: "ABOUT",
    assetKey: "laptopSprite",
    x: 128,
    y: 118,
    width: 48,
    height: 44,
    interactionRadius: 56,
    interactionPrompt: "Laptop - press E to read desk notes.",
    actionType: "dialogue",
    targetSection: "about",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "book",
    displayName: "Book",
    label: "SKILLS",
    assetKey: "bookSprite",
    x: 342,
    y: 118,
    width: 34,
    height: 38,
    interactionRadius: 50,
    interactionPrompt: "Book - press E to inspect skills.",
    actionType: "menu",
    targetSection: "skills",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "ticket",
    displayName: "Ticket",
    label: "FEATURED",
    assetKey: "ticketSprite",
    x: 586,
    y: 112,
    width: 58,
    height: 36,
    interactionRadius: 54,
    interactionPrompt: "Ticket - press E for featured memories.",
    actionType: "menu",
    targetSection: "featured",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "door",
    displayName: "Door",
    label: "PROJECTS",
    assetKey: "doorSprite",
    x: 708,
    y: 236,
    width: 40,
    height: 58,
    interactionRadius: 58,
    interactionPrompt: "Door - press E to open all projects.",
    actionType: "menu",
    targetSection: "projects",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "remote",
    displayName: "Remote",
    label: "SIM",
    assetKey: "remoteSprite",
    x: 112,
    y: 324,
    width: 30,
    height: 50,
    interactionRadius: 52,
    interactionPrompt: "Remote - press E to launch simulations.",
    actionType: "menu",
    targetSection: "simulations",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "piano",
    displayName: "Piano",
    label: "MEDIA",
    assetKey: "pianoSprite",
    x: 486,
    y: 334,
    width: 72,
    height: 34,
    interactionRadius: 58,
    interactionPrompt: "Piano - press E to browse media.",
    actionType: "menu",
    targetSection: "media",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "watch",
    displayName: "Watch",
    label: "LOGS",
    assetKey: "watchSprite",
    x: 230,
    y: 250,
    width: 30,
    height: 48,
    interactionRadius: 50,
    interactionPrompt: "Watch - press E to trace experience.",
    actionType: "menu",
    targetSection: "experience",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "tag",
    displayName: "Tag",
    label: "RESUME",
    assetKey: "tagSprite",
    x: 644,
    y: 338,
    width: 36,
    height: 48,
    interactionRadius: 52,
    interactionPrompt: "Tag - press E to open resume.",
    actionType: "menu",
    targetSection: "resume",
    color: 0xffffff,
    accent: 0x111111,
  },
  {
    id: "phone",
    displayName: "Phone",
    label: "CONTACT",
    assetKey: "phoneSprite",
    x: 420,
    y: 214,
    width: 30,
    height: 46,
    interactionRadius: 52,
    interactionPrompt: "Phone - press E to send a signal.",
    actionType: "menu",
    targetSection: "contact",
    color: 0xffffff,
    accent: 0x111111,
  },
];

export const roomObjects: RoomObject[] = interactableObjects.map((object) => ({
  object_id: object.id,
  display_name: object.displayName,
  position: { x: object.x, y: object.y },
  size: { width: object.width, height: object.height },
  interaction_radius: object.interactionRadius,
  interaction_type: object.actionType,
  linked_portfolio_section: object.targetSection,
  color: object.color,
  accent: object.accent,
  label: object.label,
  assetKey: object.assetKey,
  interactionPrompt: object.interactionPrompt,
}));
