Write-Host ""
Write-Host "Ayaan's Room commands"
Write-Host "-----------------"
Write-Host "make setup          Create missing .env files and install dependencies"
Write-Host "make dev            Setup if needed, then run frontend and backend together"
Write-Host "make test           Run frontend Vitest and backend pytest"
Write-Host "make build          Build the frontend and run backend tests"
Write-Host "make frontend-dev   Run only the Vite frontend"
Write-Host "make backend-dev    Run only the FastAPI backend"
Write-Host "make clean          Remove generated build/test output"
Write-Host ""
